### ISSUE TITLE
RFE: build uharfbuzz against system isnatlled harfbuzz library

### ISSUE THREAD

**Issue by kloczek** [harfbuzz/uharfbuzz#180] opened 2023-12-10 14:22 UTC
Please provide build procedure allowing build `uharfbuzz` against system installed harfbuzz library.

**Comment by behdad** [comment] 2023-12-10 22:57
That would indeed make more sense for Linux distro packaging.

**Comment by kloczek** [comment] 2024-05-17 20:14
Any progress? 🤔

**Comment by khaledhosny** [comment] 2024-08-04 23:49
Duplicate of #45

**Closed by khaledhosny** 2024-08-04 23:49 UTC
